version: "3.8"

services:
  servicer:
    container_name: servicer
    build:
      context: .
    restart: unless-stopped
    ports:
    - 5000:5000
    networks:
      default:
        external: true
        name: easydb_default

