version: "3.8"

services:
  servicer:
    container_name: servicer
    build:
      context: .
    restart: unless-stopped
    ports:
    - 5001:5000
    networks:
      hostnet: {}
    volumes:
    - ./app:/opt/app

networks:
  hostnet:
    external: true
    name: easydb_default

